Add paxos
Still buggy, need to figure out right template arguments for make_event. See bug
below:

paxos.tcc:207:25: error: no matching function for call to 'make_event'
    mpfds[i]->call(req, tamer::make_event<Json>(r, /* the tamer::rendezvous */
                        ^~~~~~~~~~~~~~~~~~~~~~~
mprpc/tamer/tamer/event.hh:1369:22: note: candidate function [with R = Json, T0 = unsigned long long, T1 = Json] not viable: no known conversion from
      'tamer::rendezvous<uint64_t>' to 'zero_argument_rendezvous_tag<Json> &' for 1st argument
inline event<T0, T1> make_event(zero_argument_rendezvous_tag<R>& r, T0& x0, T1& x1)
                     ^
mprpc/tamer/tamer/event.hh:1375:18: note: candidate function [with R = Json, I = unsigned long long, T0 = Json] not viable: no known conversion from 'tamer::rendezvous<uint64_t>'
      to 'one_argument_rendezvous_tag<Json> &' for 1st argument
inline event<T0> make_event(one_argument_rendezvous_tag<R>& r, const I& eid, T0& x0)
                 ^